#!/usr/bin/env python3
"""Print the catalog: per-shot state, and (with --write) regenerate CATALOG.md.

State is always computed live from shots.yaml + select.json + the actual
contents of stills/raw, stills/selected, audio/narration, and takes/ -- see
common.compute_state for the exact precedence. This script never mutates
anything by default; --write is the only flag that touches disk (CATALOG.md).
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402

STATE_LABEL = {
    "needs_prompt": "needs_prompt",
    "awaiting_still": "awaiting_still",
    "needs_select": "needs_select",
    "ready": "ready",
    "blocked": "blocked",
}


def gather_rows(config: dict, shots_doc: dict) -> list[dict]:
    select_data = common.load_select(config)
    raw_by_shot = common.all_raw_files(config)

    rows = []
    for shot in sorted(shots_doc["shots"], key=lambda s: s["publish_order"]):
        state, notes = common.compute_state(config, shot, select_data, raw_by_shot)
        has_take = common.latest_take(config, shot["id"]) is not None
        rows.append({
            "id": shot["id"],
            "act": shot["act"],
            "publish_order": shot["publish_order"],
            "priority": shot["production_priority"],
            "state": state,
            "take_rendered": has_take,
            "notes": "; ".join(notes),
        })
    return rows


def print_table(rows: list[dict]) -> None:
    widths = {"id": 28, "act": 3, "priority": 8, "state": 15, "take": 5}
    header = (
        f"{'ID':<{widths['id']}} {'Act':<{widths['act']}} "
        f"{'Priority':<{widths['priority']}} {'State':<{widths['state']}} "
        f"{'Take':<{widths['take']}} Notes"
    )
    print(header)
    print("-" * len(header))
    for r in rows:
        print(
            f"{r['id']:<{widths['id']}} {r['act']:<{widths['act']}} "
            f"{r['priority']:<{widths['priority']}} {r['state']:<{widths['state']}} "
            f"{('yes' if r['take_rendered'] else '-'):<{widths['take']}} {r['notes']}"
        )

    counts = {}
    for r in rows:
        counts[r["state"]] = counts.get(r["state"], 0) + 1
    print()
    summary = ", ".join(f"{state}: {counts.get(state, 0)}" for state in common.STATES)
    print(f"Total {len(rows)} shots -- {summary}")
    rendered = sum(1 for r in rows if r["take_rendered"])
    print(f"{rendered}/{len(rows)} shots have a rendered take")


def write_catalog_md(config: dict, shots_doc: dict, rows: list[dict]) -> Path:
    counts = {}
    for r in rows:
        counts[r["state"]] = counts.get(r["state"], 0) + 1
    rendered = sum(1 for r in rows if r["take_rendered"])

    lines = []
    lines.append("# Det sjunde sälet — Catalog")
    lines.append("")
    lines.append(f"_Generated by `status.py --write` at {datetime.now(timezone.utc).isoformat(timespec='seconds')}_")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **{len(rows)}** shots total")
    for state in common.STATES:
        lines.append(f"- **{state}**: {counts.get(state, 0)}")
    lines.append(f"- **{rendered}/{len(rows)}** shots have a rendered take")
    lines.append("")

    by_act: dict[int, list[dict]] = {}
    for r in rows:
        by_act.setdefault(r["act"], []).append(r)

    for act in sorted(by_act):
        lines.append(f"## Act {act}")
        lines.append("")
        lines.append("| Order | Shot ID | Priority | State | Take rendered | Notes |")
        lines.append("|---|---|---|---|---|---|")
        for r in by_act[act]:
            notes = r["notes"] or ""
            lines.append(
                f"| {r['publish_order']} | `{r['id']}` | {r['priority']} | {r['state']} | "
                f"{'yes' if r['take_rendered'] else '—'} | {notes} |"
            )
        lines.append("")

    out_path = common.path_for(config, "catalog_file")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate CATALOG.md")
    args = parser.parse_args(argv)

    config = common.load_config()
    shots_doc = common.load_shots(config)
    rows = gather_rows(config, shots_doc)

    print_table(rows)

    if args.write:
        out_path = write_catalog_md(config, shots_doc, rows)
        print(f"\nwrote {out_path.relative_to(common.ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
